apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "devices.kubeedge.io:devices:controller"
rules:
  - apiGroups:
    - "devices.kubeedge.io"
    resources:
      - "devices"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
      - patch