apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: kubeedge-demo
spec:
  type: ClusterIP
  selector:
    app: controller
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090