apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "devices.kubeedge.io:devices:reader"
rules:
  - apiGroups:
    - "devices.kubeedge.io"
    resources:
      - "devices"
    verbs:
      - get
      - list
      - watch
  #link the ClusterRole to the namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "devices.kubeedge.io:devices:devices-reader"
subjects:
  - kind: ServiceAccount
    name: default
    namespace: controller
roleRef:
  kind: ClusterRole
  name: "devices.kubeedge.io:device:reader"
  apiGroup: rbac.authorization.k8s.io